/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphics;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;



public class BarChartPanel extends javax.swing.JPanel {

    private double income;
    private double expense;

    public BarChartPanel() {
        initComponents();
    }

    public BarChartPanel(double income, double expense) {
        this.income = income;
        this.expense = expense;
        setPreferredSize(new Dimension(300, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        int barWidth = 100;
        int chartHeight = 150;
        double max = Math.max(income, expense);
        int incomeHeight = (int) ((income / max) * chartHeight);
        int expenseHeight = (int) ((expense / max) * chartHeight);

        
        g2.setColor(Color.BLUE);
        g2.fillRect(50, chartHeight - incomeHeight + 20, barWidth, incomeHeight);
        g2.setColor(Color.BLACK);
        g2.drawString("Income", 70, chartHeight + 40);
        g2.drawString(String.format("%.2f TL", income), 55, chartHeight - incomeHeight + 15);

        
        g2.setColor(Color.RED);
        g2.fillRect(200, chartHeight - expenseHeight + 20, barWidth, expenseHeight);
        g2.setColor(Color.BLACK);
        g2.drawString("Expense", 215, chartHeight + 40);
        g2.drawString(String.format("%.2f TL", expense), 205, chartHeight - expenseHeight + 15);
    }



    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
