/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphics;

import javax.swing.*;
import java.awt.*;

public class ReportChartPanel extends javax.swing.JPanel {

    private double incomeTL, incomeUSD, incomeEUR;
    private double expenseTL, expenseUSD, expenseEUR;

    public ReportChartPanel(double incomeTL, double incomeUSD, double incomeEUR, double expenseTL, double expenseUSD, double expenseEUR) {
        initComponents();
        setPreferredSize(new Dimension(300, 300));
        this.incomeTL = incomeTL;
        this.incomeUSD = incomeUSD;
        this.incomeEUR = incomeEUR;
        this.expenseTL = expenseTL;
        this.expenseUSD = expenseUSD;
        this.expenseEUR = expenseEUR;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        double total = incomeTL + incomeEUR + incomeUSD + expenseTL + expenseUSD + expenseEUR;
        if (total == 0) {
            return;
        }

        int startAngle = 0;

        int width = 200;
        int height = 200;
        int centerX = 50;
        int centerY = 50;

        Graphics2D g2 = (Graphics2D) g;

        // TL
        int angleIncomeTL = (int) ((incomeTL / total) * 360);
        g2.setColor(Color.BLUE);
        g2.fillArc(centerX, centerY, width, height, startAngle, angleIncomeTL);
        startAngle += angleIncomeTL;

        int angleExpenseTL = (int) ((expenseTL / total) * 360);
        g2.setColor(Color.RED);
        g2.fillArc(centerX, centerY, width, height, startAngle, angleExpenseTL);
        startAngle += angleExpenseTL;

        // USD
        int angleIncomeUSD = (int) ((incomeUSD / total) * 360);
        g2.setColor(Color.GREEN);
        g2.fillArc(centerX, centerY, width, height, startAngle, angleIncomeUSD);
        startAngle += angleIncomeUSD;

        int angleExpenseUSD = (int) ((expenseUSD / total) * 360);
        g2.setColor(Color.MAGENTA);
        g2.fillArc(centerX, centerY, width, height, startAngle, angleExpenseUSD);
        startAngle += angleExpenseUSD;

        // EUR

        int angleIncomeEUR = (int) ((incomeEUR / total) * 360);
        g2.setColor(Color.ORANGE);
        g2.fillArc(centerX, centerY, width, height, startAngle, angleIncomeEUR);
        startAngle += angleIncomeEUR;
        
        int angleExpenseEUR = (int) ((expenseEUR / total) * 360);
        g2.setColor(Color.PINK);
        g2.fillArc(centerX, centerY, width, height, startAngle, angleExpenseEUR);
        startAngle += angleExpenseEUR;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
